### ISSUE TITLE
incoherent python and scipy version requirements

### ISSUE THREAD

**Issue by alexbovet** [alexbovet/flow_stability#22]
The README says Python3 (>=3.6) and the requirements.txt says scipy>=1.12.0, but scipy 1.12.0 requires Python 3.9+. 
Do we really need scipy 1.12? if yes, we should update the Python version requirement.

**Comment by j-i-l** [comment]
Nope, we can rely on older versions of `scipy`, however, Python 3.6 was released 8 years ago, it would make sense to use a less ancient version as development basis. I'd go with 3.9, which was released in 2020 and should run on most systems (even old ones) that are still in use.

**Comment by alexbovet** [comment]
Should we add the python requirement in the requirements.txt?

**Comment by j-i-l** [comment]
> Should we add the python requirement in the requirements.txt?

The `requirements.txt` specifies dependencies within the python environment.

The python version should go into the `pyproject.toml`, here:

https://github.com/alexbovet/flow_stability/blob/main/pyproject.toml#L8

And can be specified in the README as information.

I'll setup a python 3.9 dev. environment, let `pip` figure out the correct versions, as well as, the minimal set of dependencies to install and update the pyproject.toml and req..txt accordingly.
