### ISSUE TITLE
Proper Versioning

### ISSUE THREAD

**Issue by j-i-l** [alexbovet/flow_stability#26]
Sticking to a versioning standard (Suggestion: [semver](semver.org)) will lead to a history that is also informative for new users/developers and provide the possibility to better control which state we want to release or recommend for usage.

We could simply use the "stubbed versioning" defined and described in https://github.com/t4d-gmbh/stubbed_versioning

**Comment by j-i-l** [comment]
@alexbovet should we start using the release process described here?: https://github.com/t4d-gmbh/stubbed_versioning

**Comment by alexbovet** [comment]
yes, sounds good!
