### ISSUE TITLE
OSI approved license

### ISSUE THREAD

**Issue by j-i-l** [alexbovet/flow_stability#7]
Software must be open source as per [OSI definition](https://opensource.org/osd)

**Comment by j-i-l** [comment]
We have both:

https://github.com/alexbovet/flow_stability/blob/main/COPYING

and 

https://github.com/alexbovet/flow_stability/blob/main/COPYING.LESSER

Both are OSI approved, however, I'm not sure if they can be used jointly.

Probably using one should be enough.

**Comment by alexbovet** [comment]
From what I understood, it is necessary to have both files for other LGPL3 : https://www.gnu.org/licenses/gpl-howto.en.html
