### ISSUE TITLE
How to host any paper specific content?

### ISSUE THREAD

**Issue by j-i-l** [alexbovet/flow_stability#9]
> Your paper (`paper.md` and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

We need to decide what setup we want to choose.

**Comment by j-i-l** [comment]
Having a dedicated branch on which we collect only commit specific to the content of the paper seems a sensible approach to me.

**Comment by alexbovet** [comment]
Yes, sounds good to me.

**Comment by j-i-l** [comment]
Started with the dedicated branch: https://github.com/alexbovet/flow_stability/tree/paper
